sdv/sdvapp/urls.py
# ===================
# author: Peter Lacko
# year: 2016
# ===================

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'sdvapp'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^home/$', views.HomeView.as_view(), name='home'),
    url(r'^login/', auth_views.login, {'template_name': 'sdvapp/login.html'}, name='login'),
    url(r'^logout/',
        auth_views.logout,
        {'template_name': 'sdvapp/logout.html'},
        name='logout'),
    url(r'^invite/', views.CreateInvitation.as_view(), name='invitation'),
    url(r'^register/submit/',
        views.RegistrationSubmitView.as_view(),
        name='registration_submit'),
    url(r'^register/(?P<invitation_id>[0-9a-zA-Z]{32})/',
        views.RegistrationView.as_view(),
        name='registration_access'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    # get requests here
    url(r'^resources/get/privkey/',
        views.PrivateKeyHandler.as_view(),
        name='res_get_privkey'),
    url(r'^resources/get/certificate/',
        views.CertificateHandler.as_view(),
        name='res_get_certificate'),
    url(r'^resources/newdocumentuploadform/$',
        views.NewFileUploadForm.as_view(),
        name='res_newfileuploadform'),
    url(r'^resources/get/newversionuploadform/$',
        views.NewVersionUploadForm.as_view(),
        name='res_newversionuploadform'),
    url(r'^resources/organization/certificates/.*$',
        views.OrganizationCertificates.as_view(),
        name='res_organization_certificates'),
    url(r'^resources/organization/signators/.*$',
        views.OrganizationSignators.as_view(),
        name='res_organization_signators'),
    url(r'^resources/document/details/.*$',
        views.DocumentDetails.as_view(),
        name='res_get_document_details'),
    url(r'^resources/document/signaturesbatch/.*$',
        views.DocumentSignaturesBatch.as_view(),
        name='res_document_signatures_batch'),
    url(r'^resources/documentversion/details/.*$',
        views.DocumentVersionDetails.as_view(),
        name='res_documentversion_details'),
    url(r'^resources/documentversion/signaturesbatch/.*$',
        views.DocumentVersionSignaturesBatch.as_view(),
        name='res_document_version_signatures_batch'),
    url(r'^resources/get/ddd/.*$',
        views.DocumentDecryptionData.as_view(),
        name='res_get_ddd'),
    url(r'^resources/document/version/$',
        views.DocumentVersionHandler.as_view(),
        name='res_documentversion'),
    url(r'^resources/document/history/$',
        views.DocumentCollaboration.as_view(),
        name='res_documentcollaboration'),
    url(r'^resources/document/signature/$',
        views.DocumentVersionSignature.as_view(),
        name='res_post_signature'),
    url(r'^resources/document/$',
        views.DocumentHandler.as_view(),
        name='res_document'),
]

sdv/sdvproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('sdvapp.urls')),
    url(r'^', include('two_factor.urls', 'two_factor')),
    # url(r'^polls/', include('polls.urls')),
]

sdv/sdvapp/views.py
# ===================
# author: Peter Lacko
# year: 2016
# ===================

# Django views file
import json
from datetime import datetime, timedelta
from uuid import uuid4
from urllib.parse import urlsplit, urlunsplit

from django.http import (
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseForbidden,
    HttpResponseNotFound,
    JsonResponse,
)
from django.shortcuts import render

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist, ValidationError
# from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.core.signing import Signer
from django.db import transaction
from django.db import IntegrityError
from django.db.models import Q, Max

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.decorators.http import require_safe, require_POST
from django.views.generic import ListView
from django.views.generic.base import TemplateView

from .exceptions import (
    InvitationExistsException,
    UserExistsException,
)
from .models import (
    Certificate,
    DocumentContainer,
    DocumentVersion,
    Invitation,
    Organization,
    Signator,
    Signature,
    User,
    UserDocumentPermissions,
    UserRole,
)
from .forms import (
    AccessRegistrationForm,
    InvitationForm,
    NewFileUploadForm,
    NewVersionUploadForm,
    RegistrationForm,
)
from .utils.crypto import MyCertificateHandler


class IndexView(TemplateView):
    template_name = 'sdvapp/index.html'


class HomeView(LoginRequiredMixin, TemplateView):
    """Default view for user after login. """
    http_method_names = ['get']
    docs_template = 'sdvapp/user/home.html'

    def get(self, request, *args, **kwargs):
        """Handle all get requests on 'home' view."""
        files = DocumentContainer.objects.filter(
            document_permissions_set__user=request.user,
            document_permissions_set__can_view=True).distinct()
        return render(request, self.docs_template, {'documents': files})


class CreateInvitation(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    http_method_names = ['get', 'post']
    invitation_template = 'sdvapp/invitation/invite.html'
    invited_template = 'sdvapp/invitation/confirmed.html'
    form_class = InvitationForm
    organizations_admin = []
    uuid = None
    secret_code = None

    # if this is a POST request we need to process the form data
    def post(self, request, *args, **kwargs):
        form = self.form_class(
            request.POST,
            organizations=self.organizations_admin)
        if form.is_valid():
            self.process_form(form)
            url_parsed = urlsplit(request.build_absolute_uri())
            path = reverse(
                'sdvapp:registration_access',
                current_app=self.request.resolver_match.namespace,
                args=(self.uuid,))
            url = urlunsplit((url_parsed.scheme, url_parsed.netloc, path, '', ''))
            return render(
                request, self.invited_template,
                {
                    'url': url,
                    'secret_code': self.secret_code
                })
        return render(request, self.invitation_template, {'form': form})

    # if a GET (or any other method) we'll create a blank form
    def get(self, request, *args, **kwargs):
        form = self.form_class(organizations=self.organizations_admin)
        return render(request, self.invitation_template, {'form': form})

    def test_func(self):
        self.organizations_admin = list(Organization.objects.filter(
            user__email=self.request.user.email,
            userrole__superuser=True,
        ))
        if not self.organizations_admin:
            return False
        return True

    def process_form(self, form):
        organization = form.cleaned_data['organizations']
        user_name = form.cleaned_data['user_name']
        email = form.cleaned_data['email']
        phone = form.cleaned_data['phone']
        superuser = form.cleaned_data['superuser']
        can_invite = form.cleaned_data['can_invite']
        can_view = form.cleaned_data['can_view']
        can_comment = form.cleaned_data['can_comment']
        can_sign = form.cleaned_data['can_sign']
        can_modify = form.cleaned_data['can_modify']
        can_remove = form.cleaned_data['can_remove']
        # permissions = form.cleaned_data['default_file_permissions']

        # custom generated values
        reg_uuid = str(uuid4()).replace('-', '')
        expiration = datetime.now() + timedelta(days=1)
        secret_code = str(uuid4())[:5]

        # Check if user with given name or phone already exists.
        user_exists = User.objects.filter(Q(email=email) | Q(phone=phone))
        if user_exists:
            raise UserExistsException
        invitation_exists = Invitation.objects.filter(
            Q(email=email) | Q(phone=phone))
        if invitation_exists:
            raise InvitationExistsException

        inv = Invitation(
            reg_uuid=reg_uuid,
            user_name=user_name,
            email=email,
            phone=phone,
            organization=Organization.objects.get(id=organization),
            superuser=superuser,
            can_invite=can_invite,
            can_view=can_view,
            can_comment=can_comment,
            can_modify=can_modify,
            can_sign=can_sign,
            can_remove=can_remove,
            expiration=expiration,
            secret_code=secret_code)
        inv.save()
        self.uuid = reg_uuid
        self.secret_code = secret_code


class RegistrationView(TemplateView):
    """Class for accessing Registration view"""
    http_method_names = ['get', 'post']
    access_template = "sdvapp/registration/access.html"
    registration_template = "sdvapp/registration/register.html"
    access_form_class = AccessRegistrationForm
    registration_form_class = RegistrationForm

    def get(self, request, *args, **kwargs):
        access_form = self.access_form_class()
        invitation_id = kwargs.pop('invitation_id')
        if Invitation.objects.get(reg_uuid=invitation_id) is None:
            return HttpResponseNotFound()
        return render(
            request, self.access_template,
            {
                'form': access_form,
                'access_url': '/register/{}/'.format(invitation_id)
            })

    def post(self, request, *args, **kwargs):
        invitation_id = kwargs.pop('invitation_id')
        access_form = self.access_form_class(request.POST)
        if access_form.is_valid():
            if not self.check_secret_code(access_form, invitation_id):
                return render(
                    request, self.access_template,
                    {'form': access_form, 'wrong_code': True}, status=404)
            inv_data = Invitation.objects.filter(reg_uuid=invitation_id).values()[0]
            signer = Signer()
            signature = signer.sign(invitation_id)
            inv_data['signature'] = signature
            registration_form = self.registration_form_class(inv_data=inv_data)
            return render(
                request, self.registration_template,
                {'form': registration_form})

        return render(
            request, self.access_template,
            {'form': access_form})

    def check_secret_code(self, form, invitation_id):
        inv = Invitation.objects.get(reg_uuid=invitation_id)
        if not inv:
            raise HttpResponseNotFound()
        if inv.secret_code != form.cleaned_data['secret_code']:
            return False
        return True


class RegistrationSubmitView(TemplateView):
    """Handle last step in user registration."""
    http_method_names = ['post']
    registration_form_class = RegistrationForm
    registration_submit_template = "sdvapp/registration/submit.html"

    def post(self, request, *args, **kwargs):
        reg_form = self.registration_form_class(request.POST)
        if reg_form.is_valid():
            # Raise an exception if signature is broken
            signer = Signer()
            invitation_id = signer.unsign(reg_form.cleaned_data['signature'])
            self.process_form(reg_form, invitation_id)
            # Delete invitation
            Invitation.objects.filter(reg_uuid=invitation_id).delete()
            return render(request, self.registration_submit_template)
        else:
            raise ValidationError("Form Validation Error", code='validate')

    def process_form(self, form, invitation_id):
        inv_data = Invitation.objects.get(reg_uuid=invitation_id)
        # create user object
        user = User.objects.create_user(
            name=inv_data.user_name,
            email=inv_data.email,
            password=form.cleaned_data['login_pwd'],
            phone=inv_data.phone,
            address=form.cleaned_data['address'])

        user.pubkey = form.cleaned_data['pub_key']
        user.privkey = form.cleaned_data['priv_key']

        # create role for user
        user_role = UserRole(
            user=user,
            organization=inv_data.organization,
            superuser=inv_data.superuser,
            can_invite=inv_data.can_invite,
            can_view=inv_data.can_view,
            can_comment=inv_data.can_comment,
            can_modify=inv_data.can_modify,
            can_sign=inv_data.can_sign,
            can_remove=inv_data.can_remove,
        )

        # generate certificate for user
        my_cert = MyCertificateHandler.generate_new(form.cleaned_data['csr'])
        cert = Certificate(certificate=my_cert, valid=True, owner=user)
        user.save()
        user_role.save()
        cert.save()


class ProfileView(LoginRequiredMixin, TemplateView):
    """Handles user's configuration."""
    template = "sdvapp/user/profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):

sdv/sdvapp/templates/sdvapp/user/home.html
{% extends "sdvapp/base.html" %} {% load staticfiles %} {% block head %}
<script src="{% static 'sdvapp/js/home.js' %}"></script>
<script src="{% static 'sdvapp/js/difflib/difflib.js' %}"></script>
<script src="{% static 'sdvapp/js/difflib/diffview.js' %}"></script>
{% endblock %} {% block content %} {% if documents %}
<h2>Documents:</h2>
<table id="doctable" class="tablesorter">
    <thead>
        <tr>
            <th class="id">Id</th>
            <th>Name</th>
            <th>Version</th>
            <th>Owner</th>
            <th>Status</th>
            <th>Size</th>
        </tr>
    </thead>
    <tbody>
        {% for doc in documents %}
        <tr id="docrow_{{ doc.id }}">
            <td class="id">{{ doc.id }}</td>
            <td class="name">{{ doc.name }}</td>
            <td class="version">{{ doc.current_version.version }}</td>
            <td>{{ doc.current_version.user.email }}</td>
            <td>{{ doc.status }}</td>
            <td class="size">{{ doc.current_version.size }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No documents are available.</p>
{% endif %}
<p class="pbtn" id="newfilebtn">Upload new file</p>

<div class="backgrounddiv" id="newfilebackgrounddiv"></div>
<div class="filemenu" id="filemenudiv">
    <ul class="filemenu">
        <li id="menu_get_latest">Get Latest Version</li>
        <li id="menu_upload_new_version">Upload new Version</li>
        <li id="menu_sign_latest">Sign Latest Version</li>
        <li id="menu_compare">Compare Document Versions</li>
        <li id="menu_delete">Delete Document</li>
        <li id="menu_more">Document Details</li>
        <li id="menu_history">Collaboration History</li>
    </ul>
</div>

<div class="backgrounddiv" id="ddetailsbackgrounddiv">
    <div class="centerclass" id="ddetailscenterdiv">
        <span id="ddetailsspan"></span>
        <span id="dversiondetailsspan"></span>
        <p class="pbtn" id="ddownloadbtn">Get This Version</p>
        <p class="pbtn" id="dverifysignaturesbtn">Signatures Details</p>
        <p class="pbtn" id="ddetailsdismissbtn">Close</p>
    </div>
</div>

<div class="backgrounddiv" id="sdetailsbackgrounddiv">
    <div class="centerclass" id="sdetailsdiv">
        <h3 id="sdetailsh3"></h3>
        <table id="sdetailstable"></table>
        <p class="alert" id="sdetailsalert"></p>
        <p class="pbtn" id="sdetailsdismissbtn">OK</p>
        <p class="pbtn" id="sdetailsverifybtn">Verify All Signatures</p>
    </div>
</div>

<div class="backgrounddiv" id="dcomparebackgrounddiv">
    <div class="centerclass" id="dcomparediv">
        <h3>Compare documents</h3>
        <div id="dcomparetable"></div>
        <p class="alert" id="dcomparealert"></p>
        <p class="pbtn" id="dcomparecomparebtn">Comapare selected</p>
        <p class="pbtn" id="dcomparedismissbtn">Close</p>
    </div>
</div>

<div class="backgrounddiv" id="ddiffbackgrounddiv">
    <div class="centerclass" id="outerdiffdiv">
        <div id="ddiffviewdiv"></div>
        <p class="pbtn" id="ddiffdismissbtn">Close</p>
    </div>
</div>

<div class="backgrounddiv" id="dhistorybackgrounddiv">
    <div class="centerclass" id="dhistoryviewdiv">
        <div id="dhistorytablediv"></div>
        <p class="pbtn" id="dhistorydismissbtn">Close</p>
    </div>
</div>

{% endblock %}

sdv/sdvapp/templates/sdvapp/user/profile.html
{% extends "sdvapp/base.html" %}
{% load staticfiles %}
{% block head %}
<script>
$(document).ready(function() {
    // load common functionality
    baseScript();
});
</script>
{% endblock %}
{% block content %}
<h2>Account Management</h2>
<h3>Default Permissions</h3>
<table class="tablesorter">
<tr>
    <th>Organization</th>
    <th>Admnistrator</th>
    <th>Invite</th>
    <th>View</th>
    <th>Comment</th>
    <th>Sign</th>
    <th>Modify</th>
    <th>Remove</th>
</tr>
{% for role in roles %}
<tr>
    <td>{{ role.organization }}</td>
    <td>{{ role.superuser }}</td>
    {% if role.can_invite %}
    <td><a href="{% url 'sdvapp:invitation' %}">Invite User</a></td>
    {% else %}
    <td>False</td>
    {% endif %}
    <td>{{ role.can_view }}</td>
    <td>{{ role.can_comment }}</td>
    <td>{{ role.can_sign }}</td>
    <td>{{ role.can_modify }}</td>
    <td>{{ role.can_remove }}</td>
</tr>
{% endfor %}
</table>
{% endblock %}