sdv/sdvapp/urls.py
# ===================
# author: Peter Lacko
# year: 2016
# ===================

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'sdvapp'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^home/$', views.HomeView.as_view(), name='home'),
    url(r'^login/', auth_views.login, {'template_name': 'sdvapp/login.html'}, name='login'),
    url(r'^logout/',
        auth_views.logout,
        {'template_name': 'sdvapp/logout.html'},
        name='logout'),
    url(r'^invite/', views.CreateInvitation.as_view(), name='invitation'),
    url(r'^register/submit/',
        views.RegistrationSubmitView.as_view(),
        name='registration_submit'),
    url(r'^register/(?P<invitation_id>[0-9a-zA-Z]{32})/',
        views.RegistrationView.as_view(),
        name='registration_access'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    # get requests here
    url(r'^resources/get/privkey/',
        views.PrivateKeyHandler.as_view(),
        name='res_get_privkey'),
    url(r'^resources/get/certificate/',
        views.CertificateHandler.as_view(),
        name='res_get_certificate'),
    url(r'^resources/newdocumentuploadform/$',
        views.NewFileUploadForm.as_view(),
        name='res_newfileuploadform'),
    url(r'^resources/get/newversionuploadform/$',
        views.NewVersionUploadForm.as_view(),
        name='res_newversionuploadform'),
    url(r'^resources/organization/certificates/.*$',
        views.OrganizationCertificates.as_view(),
        name='res_organization_certificates'),
    url(r'^resources/organization/signators/.*$',
        views.OrganizationSignators.as_view(),
        name='res_organization_signators'),
    url(r'^resources/document/details/.*$',
        views.DocumentDetails.as_view(),
        name='res_get_document_details'),
    url(r'^resources/document/signaturesbatch/.*$',
        views.DocumentSignaturesBatch.as_view(),
        name='res_document_signatures_batch'),
    url(r'^resources/documentversion/details/.*$',
        views.DocumentVersionDetails.as_view(),
        name='res_documentversion_details'),
    url(r'^resources/documentversion/signaturesbatch/.*$',
        views.DocumentVersionSignaturesBatch.as_view(),
        name='res_document_version_signatures_batch'),
    url(r'^resources/get/ddd/.*$',
        views.DocumentDecryptionData.as_view(),
        name='res_get_ddd'),
    url(r'^resources/document/version/$',
        views.DocumentVersionHandler.as_view(),
        name='res_documentversion'),
    url(r'^resources/document/history/$',
        views.DocumentCollaboration.as_view(),
        name='res_documentcollaboration'),
    url(r'^resources/document/signature/$',
        views.DocumentVersionSignature.as_view(),
        name='res_post_signature'),
    url(r'^resources/document/$',
        views.DocumentHandler.as_view(),
        name='res_document'),
]

sdv/sdvproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('sdvapp.urls')),
    url(r'^', include('two_factor.urls', 'two_factor')),
    # url(r'^polls/', include('polls.urls')),
]

sdv/sdvapp/models.py
# ===================
# author: Peter Lacko
# year: 2016
# ===================

"""Set of models representing database model."""

from django.db import models
from django.db.models import Max
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager
)
from django.contrib.postgres.fields import DateTimeRangeField
from .utils.utils import get_file_path
from django.core.exceptions import ObjectDoesNotExist, ValidationError


class Organization(models.Model):
    name = models.CharField(
        max_length=255,
        unique=True,
        blank=False,
        verbose_name='Organization name',
    )
    email = models.EmailField(max_length=255, unique=True, blank=False, default='change@me.now')
    phone = models.CharField(max_length=255,)
    address = models.CharField(max_length=255, verbose_name='Address')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class UserManager(BaseUserManager):

    def create_user(self, name, email, password, phone='012', address='abc'):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.name = name
        user.phone = phone
        user.address = address
        user.set_password(password)
        user.is_staff = False
        user.is_active = True
        user.save(using=self._db)
        return user

    def create_superuser(self, name, email, password,
                         phone='012', address='abc'):
        user = self.create_user(
            name=name, email=email, password=password,
            phone=phone, address=address)
        user.is_admin = True
        user.is_staff = True
        user.is_active = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    """Represents single user in the system."""
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,)
    name = models.CharField(
        max_length=255, blank=False, verbose_name='Full Name')
    phone = models.CharField(max_length=255, verbose_name='Telephone number')
    address = models.CharField(max_length=255, verbose_name='Address')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Account registered')
    pubkey = models.TextField(verbose_name='Public key')
    privkey = models.TextField(verbose_name='Private key')
    organization = models.ManyToManyField(
        Organization,
        through='UserRole')
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return self.name

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        # Simplest possible answer: Yes, always
        return True

    def can_view(self, document_id):
        """Can this user view specific document?"""
        try:
            if UserDocumentPermissions.objects.get(user=self.id, document=document_id).can_view:
                return True
            return False
        except ObjectDoesNotExist:
            return False

    def can_sign(self, document_id):
        """Can this user sign specific document?"""
        try:
            if UserDocumentPermissions.objects.get(user=self.id, document=document_id).can_sign:
                return True
            return False
        except ObjectDoesNotExist:
            return False

    def can_comment(self, document_id):
        """Can this user comment on specific document?"""
        try:
            if UserDocumentPermissions.objects.get(user=user.id, document=document_id).can_comment:
                return True
            return False
        except ObjectDoesNotExist:
            return False

    def can_modify(self, document_id):
        """Can this user modify specific document, i.e upload new version?"""
        try:
            if UserDocumentPermissions.objects.get(user=self.id, document=document_id).can_modify:
                return True
            return False
        except ObjectDoesNotExist:
            return False

    def can_remove(self, document_id):
        """Can this user view specific document?"""
        try:
            if UserDocumentPermissions.objects.get(user=self.id, document=document_id).can_remove:
                return True
            return False
        except ObjectDoesNotExist:
            return False

    def can_add_new(self, organization_id):
        """Can this user add new document to the organization workspace?"""
        try:
            if UserRole.objects.get(user=self.id, organization=organization_id).can_modify:
                return True
            return False
        except ObjectDoesNotExist:
            return False


class UserRole(models.Model):
    """This model binds user to an organization.

    Each such binding holds default user's permissions for organization.
    Permissions can be overriden locally on per-document level.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    superuser = models.BooleanField(null=False, default=False)
    can_view = models.BooleanField(null=False, default=True)
    can_comment = models.BooleanField(null=False, default=True)
    can_sign = models.BooleanField(null=False, default=True)
    can_modify = models.BooleanField(null=False, default=True)
    can_remove = models.BooleanField(null=False, default=True)
    can_invite = models.BooleanField(null=False, default=False)

    class Meta:
        unique_together = ('user', 'organization')

    def __str__(self):
        return "{org}: {user}: su={su}".format(
            org=str(self.organization),
            user=str(self.user),
            su=str(self.superuser))


class Certificate(models.Model):
    """Model holds all certificates in the system for every user."""
    certificate = models.TextField()
    valid = models.BooleanField(null=False, default=True)
    owner = models.ForeignKey(User, default=1)


class DocumentContainer(models.Model):
    """Model holds all system's documents in tree-like structure.

    Every document is uniquely identified by path and name. If name field
    is empty string, entry emulates directory function.
    """
    organization = models.ForeignKey(Organization, default=1)
    # name of the file as provided by user
    name = models.CharField(max_length=255)
    # Virtual path to the file managed by database
    # TODO: write ltree field
    path = models.CharField(null=False, max_length=255, default='/')
    description = models.TextField(null=True)
    DOC_STATUS = (
        ('IP', 'In Progress'),
        ('CA', 'Rejected'),
        ('AP', 'Approved'),
    )
    status = models.CharField(max_length=2, choices=DOC_STATUS, default='IP')
    lock_owner = models.ForeignKey(
        User, null=True, default=None, related_name='user_locks')
    lock = DateTimeRangeField(null=True)
    archived = models.BooleanField(default=False, db_index=True)
    date_archived = models.DateTimeField(null=True)
    user = models.ManyToManyField(User, through='UserDocumentPermissions')
    due_date = models.DateTimeField(auto_now_add=False, null=True)

    def __str__(self):
        return self.path + self.name

    def current_version(self):
        """Returns object representing current version of document."""
        version = DocumentVersion.objects.filter(
            document=self.id).aggregate(Max('version'))['version__max']
        return DocumentVersion.objects.get(document=self.id, version=version)


class UserDocumentPermissions(models.Model):
    """Per-document user permissions. Superior to default permissions."""
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_permissions_set")
    document = models.ForeignKey(
        DocumentContainer,
        on_delete=models.CASCADE,
        related_name="document_permissions_set")
    document_key = models.TextField(null=True)
    can_view = models.BooleanField(null=False, default=True)
    can_comment = models.BooleanField(null=False, default=True)
    can_sign = models.BooleanField(null=False, default=True)
    can_modify = models.BooleanField(null=False, default=True)
    can_remove = models.BooleanField(null=False, default=True)

    class Meta:
        unique_together = ('user', 'document')


class DocumentVersion(models.Model):
    document = models.ForeignKey(DocumentContainer, on_delete=models.CASCADE)
    user = models.ForeignKey(User)
    version = models.IntegerField(null=False, default=1)
    # real path to the file on filesystem
    # storage_path = models.FileField(upload_to=get_file_path, null=True)
    base64 = models.TextField(null=True)
    size = models.IntegerField(null=False, default=0)
    iv = models.TextField(null=False, blank=False, default=b'0')
    valid = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    binary = models.BooleanField(default=True)

    class Meta:
        unique_together = ('document', 'version')


class Action(models.Model):
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    action = models.CharField(max_length=255, )

    def __str__(self):
        return self.action


class Signator(models.Model):
    document = models.ForeignKey(DocumentContainer, on_delete=models.CASCADE)

sdv/sdvapp/templates/sdvapp/documents/collaborationhistory.html
{% load app_filters %}
{% load mathfilters %}
<table class="history">
    <tr>
        <th>Summary</th><th>Mandatory Signators</th><th>Other signators</th>
    </tr>
    {% for version in versions %}
    {% with mandatory=mandatory_signators.count signed=signed_ms|get_item:version.version|length %}
    {% if mandatory == 0 %}
    <tr class="unspecified">
    {% else %}
    {% with ratio=signed|div:mandatory %}
    {% if ratio < 0.5 %}
    <tr class="insufficient">
    {% elif ratio < 1 %}
    <tr class="almost">
    {% else %}
    <tr class="approved">
    {% endif %}
    {% endwith %}
    {% endif %}
        <td>
            <p>Version: {{ version.version }}</p>
            <p>Mandatory: {{ signed }}/{{ mandatory }}</p>
            <p>Total: {{ version.signature_set.count }}</p>
        </td>
        <td>
            <ul class="signators">
                {% for sig in signed_ms|get_item:version.version %}
                <li class="signed">&#10004;{{ sig.email }}</li>
                {% endfor %}

                {% for unsig in unsigned_ms|get_item:version.version %}
                <li class="unsigned">&#10008;{{ unsig.email }}</li>
                {% endfor %}
            </ul>
        </td>
        <td>
            <ul class="signators">
                {% for sig in others|get_item:version.version %}
                <li>&#10004;{{ sig.email }}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>
    {% endwith %}
    {% endfor %}
</table>

sdv/sdvapp/templates/sdvapp/documents/documentdetails.html
<table class="detailstable" id="documentdetailstable">
    <tr>
        <td class="label">Name</td><td class="value">{{ document.name }}</td>
    </tr>
    <tr>
        <td class="label">Organization</td><td class="value">{{ document.organization.name }}</td>
    </tr>
    <tr>
        <td class="label">Description</td><td class="value">{{ document.description }}</td>
    </tr>
    <tr>
        <td class="label">Status</td><td class="value">{{ document.status }}</td>
    </tr>
    <tr>
        <td class="label">Requested signators</td>
        <td class="value">
            <ul>
                {% for signator in document.signator_set.all %}
                <li>{{ signator.user.email }}</li>
                {% empty %}
                <span>No signators specified!</span>
                {% endfor %}
            </ul>
        </td>
    </tr>
</table>
<select id="dversionselect">
    {% for doc in document.documentversion_set.all reversed %}
        <option value="{{ doc.version }}">Version {{ doc.version }}</option>
    {% endfor %}
</select>

sdv/sdvapp/templates/sdvapp/documents/documentversiondetails.html
<table class="detailstable" id="versiondetailstable">
    <tr>
        <td class="label">Validity</td><td class="value">{{ document.valid }}</td>
    </tr>
    <tr>
        <td class="label">Created on</td><td class="value">{{ document.created }}</td>
    </tr>
    <tr>
        <td class="label">Uploaded by</td><td class="value">{{ document.user.email }}</td>
    </tr>
    <tr>
        <td class="label">Signed by</td>
        <td class="value">
            <ul>
                {% for signature in document.signature_set.all %}
                <li>{{ signature.user.email }}</li>
                {% empty %}
                <p>No signators!</p>
                {% endfor %}
            </ul>
        </td>
    </tr>
    <tr>
        <td class="label">Size</td><td class="value">{{ document.size }} bytes</td>
    </tr>
</table>

sdv/sdvapp/templates/sdvapp/documents/newfileupload.html
<form class="fileform centerclass" id="newfileform" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form.organizations.label_tag }} {{ form.organizations }}</p>
    <table id="newfile_signators_table"></table>
    <p>{{ form.due_date.label_tag }} {{ form.due_date }}</p>
    <p>{{ form.filefield.label_tag }} {{ form.filefield }}</p>
    <p class="alert" id="file_upload_alert"/>
    <input class="popup" type="button" id="newfile_confirm" value="Upload"/>
    <input class="popup" type="button" id="newfile_cancel" value="Cancel"/>
</form>

sdv/sdvapp/templates/sdvapp/documents/newversionupload.html
<form class="fileform centerclass" id="newversionform" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <p class="alert" id="file_upload_alert"/>
    <input class="popup" type="button" id="newversion_confirm" value="Upload"/>
    <input class="popup" type="button" id="newversion_cancel" value="Cancel"/>
</form>