sdv/sdvapp/urls.py
# ===================
# author: Peter Lacko
# year: 2016
# ===================

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'sdvapp'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^home/$', views.HomeView.as_view(), name='home'),
    url(r'^login/', auth_views.login, {'template_name': 'sdvapp/login.html'}, name='login'),
    url(r'^logout/',
        auth_views.logout,
        {'template_name': 'sdvapp/logout.html'},
        name='logout'),
    url(r'^invite/', views.CreateInvitation.as_view(), name='invitation'),
    url(r'^register/submit/',
        views.RegistrationSubmitView.as_view(),
        name='registration_submit'),
    url(r'^register/(?P<invitation_id>[0-9a-zA-Z]{32})/',
        views.RegistrationView.as_view(),
        name='registration_access'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    # get requests here
    url(r'^resources/get/privkey/',
        views.PrivateKeyHandler.as_view(),
        name='res_get_privkey'),
    url(r'^resources/get/certificate/',
        views.CertificateHandler.as_view(),
        name='res_get_certificate'),
    url(r'^resources/newdocumentuploadform/$',
        views.NewFileUploadForm.as_view(),
        name='res_newfileuploadform'),
    url(r'^resources/get/newversionuploadform/$',
        views.NewVersionUploadForm.as_view(),
        name='res_newversionuploadform'),
    url(r'^resources/organization/certificates/.*$',
        views.OrganizationCertificates.as_view(),
        name='res_organization_certificates'),
    url(r'^resources/organization/signators/.*$',
        views.OrganizationSignators.as_view(),
        name='res_organization_signators'),
    url(r'^resources/document/details/.*$',
        views.DocumentDetails.as_view(),
        name='res_get_document_details'),
    url(r'^resources/document/signaturesbatch/.*$',
        views.DocumentSignaturesBatch.as_view(),
        name='res_document_signatures_batch'),
    url(r'^resources/documentversion/details/.*$',
        views.DocumentVersionDetails.as_view(),
        name='res_documentversion_details'),
    url(r'^resources/documentversion/signaturesbatch/.*$',
        views.DocumentVersionSignaturesBatch.as_view(),
        name='res_document_version_signatures_batch'),
    url(r'^resources/get/ddd/.*$',
        views.DocumentDecryptionData.as_view(),
        name='res_get_ddd'),
    url(r'^resources/document/version/$',
        views.DocumentVersionHandler.as_view(),
        name='res_documentversion'),
    url(r'^resources/document/history/$',
        views.DocumentCollaboration.as_view(),
        name='res_documentcollaboration'),
    url(r'^resources/document/signature/$',
        views.DocumentVersionSignature.as_view(),
        name='res_post_signature'),
    url(r'^resources/document/$',
        views.DocumentHandler.as_view(),
        name='res_document'),
]

sdv/sdvproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('sdvapp.urls')),
    url(r'^', include('two_factor.urls', 'two_factor')),
    # url(r'^polls/', include('polls.urls')),
]

sdv/sdvapp/views.py
# ===================
# author: Peter Lacko
# year: 2016
# ===================

# Django views file
import json
from datetime import datetime, timedelta
from uuid import uuid4
from urllib.parse import urlsplit, urlunsplit

from django.http import (
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseForbidden,
    HttpResponseNotFound,
    JsonResponse,
)
from django.shortcuts import render

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist, ValidationError
# from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.core.signing import Signer
from django.db import transaction
from django.db import IntegrityError
from django.db.models import Q, Max

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.decorators.http import require_safe, require_POST
from django.views.generic import ListView
from django.views.generic.base import TemplateView

from .exceptions import (
    InvitationExistsException,
    UserExistsException,
)
from .models import (
    Certificate,
    DocumentContainer,
    DocumentVersion,
    Invitation,
    Organization,
    Signator,
    Signature,
    User,
    UserDocumentPermissions,
    UserRole,
)
from .forms import (
    AccessRegistrationForm,
    InvitationForm,
    NewFileUploadForm,
    NewVersionUploadForm,
    RegistrationForm,
)
from .utils.crypto import MyCertificateHandler


class IndexView(TemplateView):
    template_name = 'sdvapp/index.html'


class HomeView(LoginRequiredMixin, TemplateView):
    """Default view for user after login. """
    http_method_names = ['get']
    docs_template = 'sdvapp/user/home.html'

    def get(self, request, *args, **kwargs):
        """Handle all get requests on 'home' view."""
        files = DocumentContainer.objects.filter(
            document_permissions_set__user=request.user,
            document_permissions_set__can_view=True).distinct()
        return render(request, self.docs_template, {'documents': files})


class CreateInvitation(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    http_method_names = ['get', 'post']
    invitation_template = 'sdvapp/invitation/invite.html'
    invited_template = 'sdvapp/invitation/confirmed.html'
    form_class = InvitationForm
    organizations_admin = []
    uuid = None
    secret_code = None

    # if this is a POST request we need to process the form data
    def post(self, request, *args, **kwargs):
        form = self.form_class(
            request.POST,
            organizations=self.organizations_admin)
        if form.is_valid():
            self.process_form(form)
            url_parsed = urlsplit(request.build_absolute_uri())
            path = reverse(
                'sdvapp:registration_access',
                current_app=self.request.resolver_match.namespace,
                args=(self.uuid,))
            url = urlunsplit((url_parsed.scheme, url_parsed.netloc, path, '', ''))
            return render(
                request, self.invited_template,
                {
                    'url': url,
                    'secret_code': self.secret_code
                })
        return render(request, self.invitation_template, {'form': form})

    # if a GET (or any other method) we'll create a blank form
    def get(self, request, *args, **kwargs):
        form = self.form_class(organizations=self.organizations_admin)
        return render(request, self.invitation_template, {'form': form})

    def test_func(self):
        self.organizations_admin = list(Organization.objects.filter(
            user__email=self.request.user.email,
            userrole__superuser=True,
        ))
        if not self.organizations_admin:
            return False
        return True

    def process_form(self, form):
        organization = form.cleaned_data['organizations']
        user_name = form.cleaned_data['user_name']
        email = form.cleaned_data['email']
        phone = form.cleaned_data['phone']
        superuser = form.cleaned_data['superuser']
        can_invite = form.cleaned_data['can_invite']
        can_view = form.cleaned_data['can_view']
        can_comment = form.cleaned_data['can_comment']
        can_sign = form.cleaned_data['can_sign']
        can_modify = form.cleaned_data['can_modify']
        can_remove = form.cleaned_data['can_remove']
        # permissions = form.cleaned_data['default_file_permissions']

        # custom generated values
        reg_uuid = str(uuid4()).replace('-', '')
        expiration = datetime.now() + timedelta(days=1)
        secret_code = str(uuid4())[:5]

        # Check if user with given name or phone already exists.
        user_exists = User.objects.filter(Q(email=email) | Q(phone=phone))
        if user_exists:
            raise UserExistsException
        invitation_exists = Invitation.objects.filter(
            Q(email=email) | Q(phone=phone))
        if invitation_exists:
            raise InvitationExistsException

        inv = Invitation(
            reg_uuid=reg_uuid,
            user_name=user_name,
            email=email,
            phone=phone,
            organization=Organization.objects.get(id=organization),
            superuser=superuser,
            can_invite=can_invite,
            can_view=can_view,
            can_comment=can_comment,
            can_modify=can_modify,
            can_sign=can_sign,
            can_remove=can_remove,
            expiration=expiration,
            secret_code=secret_code)
        inv.save()
        self.uuid = reg_uuid
        self.secret_code = secret_code


class RegistrationView(TemplateView):
    """Class for accessing Registration view"""
    http_method_names = ['get', 'post']
    access_template = "sdvapp/registration/access.html"
    registration_template = "sdvapp/registration/register.html"
    access_form_class = AccessRegistrationForm
    registration_form_class = RegistrationForm

    def get(self, request, *args, **kwargs):
        access_form = self.access_form_class()
        invitation_id = kwargs.pop('invitation_id')
        if Invitation.objects.get(reg_uuid=invitation_id) is None:
            return HttpResponseNotFound()
        return render(
            request, self.access_template,
            {
                'form': access_form,
                'access_url': '/register/{}/'.format(invitation_id)
            })

    def post(self, request, *args, **kwargs):
        invitation_id = kwargs.pop('invitation_id')
        access_form = self.access_form_class(request.POST)
        if access_form.is_valid():
            if not self.check_secret_code(access_form, invitation_id):
                return render(
                    request, self.access_template,
                    {'form': access_form, 'wrong_code': True}, status=404)
            inv_data = Invitation.objects.filter(reg_uuid=invitation_id).values()[0]
            signer = Signer()
            signature = signer.sign(invitation_id)
            inv_data['signature'] = signature
            registration_form = self.registration_form_class(inv_data=inv_data)
            return render(
                request, self.registration_template,
                {'form': registration_form})

        return render(
            request, self.access_template,
            {'form': access_form})

    def check_secret_code(self, form, invitation_id):
        inv = Invitation.objects.get(reg_uuid=invitation_id)
        if not inv:
            raise HttpResponseNotFound()
        if inv.secret_code != form.cleaned_data['secret_code']:
            return False
        return True


class RegistrationSubmitView(TemplateView):
    """Handle last step in user registration."""
    http_method_names = ['post']
    registration_form_class = RegistrationForm
    registration_submit_template = "sdvapp/registration/submit.html"

    def post(self, request, *args, **kwargs):
        reg_form = self.registration_form_class(request.POST)
        if reg_form.is_valid():
            # Raise an exception if signature is broken
            signer = Signer()
            invitation_id = signer.unsign(reg_form.cleaned_data['signature'])
            self.process_form(reg_form, invitation_id)
            # Delete invitation
            Invitation.objects.filter(reg_uuid=invitation_id).delete()
            return render(request, self.registration_submit_template)
        else:
            raise ValidationError("Form Validation Error", code='validate')

    def process_form(self, form, invitation_id):
        inv_data = Invitation.objects.get(reg_uuid=invitation_id)
        # create user object
        user = User.objects.create_user(
            name=inv_data.user_name,
            email=inv_data.email,
            password=form.cleaned_data['login_pwd'],
            phone=inv_data.phone,
            address=form.cleaned_data['address'])

        user.pubkey = form.cleaned_data['pub_key']
        user.privkey = form.cleaned_data['priv_key']

        # create role for user
        user_role = UserRole(
            user=user,
            organization=inv_data.organization,
            superuser=inv_data.superuser,
            can_invite=inv_data.can_invite,
            can_view=inv_data.can_view,
            can_comment=inv_data.can_comment,
            can_modify=inv_data.can_modify,
            can_sign=inv_data.can_sign,
            can_remove=inv_data.can_remove,
        )

        # generate certificate for user
        my_cert = MyCertificateHandler.generate_new(form.cleaned_data['csr'])
        cert = Certificate(certificate=my_cert, valid=True, owner=user)
        user.save()
        user_role.save()
        cert.save()


class ProfileView(LoginRequiredMixin, TemplateView):
    """Handles user's configuration."""
    template = "sdvapp/user/profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):

sdv/sdvapp/templates/sdvapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>SDV Document Management System</title>
        <link rel="stylesheet" href="{% static 'sdvapp/css/base.css' %}">
        <script src="{% static 'sdvapp/js/pkijs/common.js' %}"></script>
        <script src="{% static 'sdvapp/js/pkijs/asn1.js' %}"></script>
        <script src="{% static 'sdvapp/js/pkijs/x509_schema.js' %}"></script>
        <script src="{% static 'sdvapp/js/pkijs/x509_simpl.js' %}"></script>
        <script src="{% static 'sdvapp/js/pkijs/cms_schema.js' %}"></script>
        <script src="{% static 'sdvapp/js/pkijs/cms_simpl.js' %}"></script>
        <script src="{% static 'sdvapp/js/pkijs/pkcs12_schema.js' %}"></script>
        <script src="{% static 'sdvapp/js/pkijs/pkcs12_simpl.js' %}"></script>
        <script src="{% static 'sdvapp/js/jquery/jquery.js' %}"></script>
        <script src="{% static 'sdvapp/js/jquery/jquery.tablesorter.js' %}"></script>
        <script src="{% static 'sdvapp/js/crypto.js' %}"></script>
        <script src="{% static 'sdvapp/js/base.js' %}"></script>
        {% block head %}{% endblock %}
    </head>

    <body>
        <ul class="navbar">
            <li><a href="{% url 'sdvapp:home' %}">Home<br/>({{ request.user }})</a>
            <li><a href="{% url 'sdvapp:profile' %}">Profile</a>
            <li><a href="{% url 'sdvapp:logout' %}">Logout</a>
            <li><p class="pbtn" id="keypassbtn">Unlock Documents</p>
        </ul>
        <div class="backgrounddiv" id="keypassbackgrounddiv">
          <form class="form centerclass" id="keypassform">
            <h3>Enter password for document decryption</h3>
            <input type="password" id="keypassinput" placeholder="type password here.."/>
            <p class="alert" id="keypass_request_alert"></p>
            <input class="popup" type="button" id="keypass_confirm" value="Confirm"/>
            <input class="popup" type="button" id="keypass_cancel" value="Cancel"/>
          </form>
        </div>
        {% block content %}{% endblock %}
    </body>
</html>

sdv/sdvapp/templates/sdvapp/index.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head/>
    <body>
        <h1>Welcome!</h1>
        To use the system, please <a href="{% url 'two_factor:login' %}">login</a>
    </body>
</html>

sdv/sdvapp/templates/sdvapp/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'sdvapp:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<!-- p><a href="{#% url 'password_reset' %}">Lost password?</a></p -->

sdv/sdvapp/templates/sdvapp/logout.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <script>
            sessionStorage.clear("privateKey");
            sessionStorage.clear("certificate");
        </script>
    </head>
    <body>
        <h2>Logged out!</h2>
    </body>
</html>